// Top ~1000 most frequent Russian words
const RUSSIAN_WORDS = [
// ── Function words ──────────────────────────────────────────────────────────
["и","and"],["в","in / at"],["не","not"],["на","on / at"],["я","I"],
["что","what / that"],["с","with / from"],["он","he"],["как","how / as / like"],
["но","but"],["это","this / it"],["она","she"],["всё","everything / all"],
["по","along / by / about"],["его","his / him"],["за","for / behind"],
["мы","we"],["из","from / out of"],["а","and / but / whereas"],["они","they"],
["то","that / then"],["от","from / away from"],["так","so / thus"],
["же","(emphatic particle)"],["тот","that one"],["бы","would (conditional)"],
["к","to / towards"],["ещё","still / yet / more"],["уже","already"],
["до","until / before / up to"],["вы","you (plural / formal)"],["или","or"],
["который","which / who"],["если","if"],["при","at / by / under"],
["наш","our"],["без","without"],["когда","when"],["даже","even"],
["вот","here is / there is"],["ли","whether (question particle)"],
["там","there"],["нет","no / there is no"],["её","her / hers"],
["их","their / them"],["об","about"],["тоже","also / too"],
["только","only / just"],["уж","already (emphatic)"],["себя","oneself"],
["своё","one's own (n/a)"],["свой","one's own"],["сам","oneself / self"],
["тогда","then / at that time"],["здесь","here"],["потом","then / afterwards"],
["всегда","always"],["очень","very / much"],["теперь","now / from now on"],
["где","where"],["куда","where (to)"],["откуда","where from"],
["почему","why"],["зачем","what for / why"],["как","how"],
["сколько","how much / how many"],["много","a lot / many"],["мало","little / few"],
["больше","more / no longer"],["меньше","less / fewer"],["лучше","better"],
["хуже","worse"],["вместе","together"],["снова","again"],["опять","again"],
["вдруг","suddenly"],["сразу","at once / immediately"],["наконец","finally"],
["уже","already"],["совсем","completely / at all"],["почти","almost"],
["просто","simply / just"],["именно","exactly / precisely"],
["конечно","of course / certainly"],["может быть","maybe / perhaps"],
["действительно","really / indeed"],["вообще","in general / at all"],
["например","for example"],["поэтому","therefore / that's why"],
["однако","however / but"],["также","also / as well"],["хотя","although / though"],
["чтобы","so that / in order to"],["потому что","because"],
["когда-нибудь","someday / ever"],["никогда","never"],["иногда","sometimes"],
["обычно","usually"],["часто","often"],["редко","rarely"],
["везде","everywhere"],["нигде","nowhere"],["всюду","everywhere"],
["далеко","far"],["близко","near / close"],["рядом","next to / nearby"],
["вперёд","forward / ahead"],["назад","back / backwards"],
["вверх","upward"],["вниз","downward"],["прямо","straight / directly"],
["налево","to the left"],["направо","to the right"],["сюда","here (to here)"],
["туда","there (to there)"],["отсюда","from here"],["оттуда","from there"],
// ── Numbers ──────────────────────────────────────────────────────────────────
["один","one"],["два","two"],["три","three"],["четыре","four"],["пять","five"],
["шесть","six"],["семь","seven"],["восемь","eight"],["девять","nine"],
["десять","ten"],["одиннадцать","eleven"],["двенадцать","twelve"],
["тринадцать","thirteen"],["четырнадцать","fourteen"],["пятнадцать","fifteen"],
["двадцать","twenty"],["тридцать","thirty"],["сорок","forty"],
["пятьдесят","fifty"],["шестьдесят","sixty"],["семьдесят","seventy"],
["восемьдесят","eighty"],["девяносто","ninety"],["сто","hundred"],
["тысяча","thousand"],["миллион","million"],["первый","first"],
["второй","second"],["третий","third"],["четвёртый","fourth"],
["пятый","fifth"],["последний","last"],["следующий","next / following"],
// ── Core verbs ───────────────────────────────────────────────────────────────
["быть","to be"],["стать","to become (perf)"],["есть","to eat / there is"],
["иметь","to have"],["мочь","to be able to / can"],["хотеть","to want"],
["знать","to know"],["думать","to think"],["говорить","to speak / say"],
["сказать","to say / tell (perf)"],["делать","to do / make"],
["сделать","to do / make (perf)"],["идти","to go (on foot)"],
["ходить","to go / walk (repeated)"],["ехать","to go (by transport)"],
["ездить","to travel (repeated)"],["бежать","to run"],["бегать","to run (repeated)"],
["давать","to give"],["дать","to give (perf)"],["брать","to take"],
["взять","to take (perf)"],["видеть","to see"],["смотреть","to look / watch"],
["слышать","to hear"],["слушать","to listen"],["читать","to read"],
["писать","to write"],["понимать","to understand"],["понять","to understand (perf)"],
["знать","to know"],["помнить","to remember"],["забыть","to forget (perf)"],
["забывать","to forget"],["верить","to believe"],["любить","to love / like"],
["жить","to live"],["умереть","to die (perf)"],["родиться","to be born (perf)"],
["работать","to work"],["учиться","to study / learn"],["играть","to play"],
["помочь","to help (perf)"],["помогать","to help"],["найти","to find (perf)"],
["искать","to search / look for"],["открыть","to open (perf)"],
["закрыть","to close (perf)"],["начать","to begin (perf)"],
["начинать","to begin"],["кончить","to finish (perf)"],
["продолжать","to continue"],["остановить","to stop (perf)"],
["остаться","to stay / remain (perf)"],["оставаться","to stay / remain"],
["вернуться","to return (perf)"],["возвращаться","to return"],
["приходить","to come / arrive"],["прийти","to come / arrive (perf)"],
["уходить","to leave / go away"],["уйти","to leave (perf)"],
["входить","to enter"],["выходить","to go out / exit"],
["подходить","to approach"],["встретить","to meet (perf)"],
["встречать","to meet"],["ждать","to wait"],["спросить","to ask (perf)"],
["спрашивать","to ask"],["ответить","to answer (perf)"],
["отвечать","to answer"],["рассказать","to tell / narrate (perf)"],
["объяснить","to explain (perf)"],["показать","to show (perf)"],
["показывать","to show"],["позвонить","to call / phone (perf)"],
["купить","to buy (perf)"],["покупать","to buy"],["продать","to sell (perf)"],
["получить","to receive / get (perf)"],["получать","to receive"],
["использовать","to use"],["создать","to create (perf)"],
["строить","to build"],["решить","to decide / solve (perf)"],
["решать","to decide / solve"],["считать","to count / consider"],
["узнать","to find out / recognise (perf)"],["узнавать","to find out"],
["выбрать","to choose (perf)"],["выбирать","to choose"],
["изменить","to change (perf)"],["изменять","to change"],
["стоить","to cost / be worth"],["казаться","to seem"],
["называться","to be called"],["происходить","to happen / occur"],
["появляться","to appear"],["исчезать","to disappear"],
["расти","to grow"],["падать","to fall"],["подниматься","to rise / go up"],
["двигаться","to move"],["бояться","to be afraid"],
["радоваться","to be glad / rejoice"],["смеяться","to laugh"],
["плакать","to cry"],["кричать","to shout"],["петь","to sing"],
["танцевать","to dance"],["готовить","to cook / prepare"],
["пить","to drink"],["спать","to sleep"],["отдыхать","to rest"],
["зависеть","to depend"],["развиваться","to develop"],
["соглашаться","to agree"],["отказываться","to refuse"],
["предлагать","to suggest / offer"],["требовать","to demand"],
["разрешать","to allow / permit"],["запрещать","to forbid"],
["защищать","to defend / protect"],["бороться","to fight / struggle"],
["нести","to carry"],["везти","to carry (by vehicle)"],
["положить","to put / place (perf)"],["класть","to put / place"],
["прятаться","to hide"],["повторять","to repeat"],
// ── Common adjectives ────────────────────────────────────────────────────────
["большой","big / large"],["маленький","small / little"],["новый","new"],
["старый","old"],["хороший","good"],["плохой","bad"],["молодой","young"],
["высокий","tall / high"],["низкий","low / short"],["длинный","long"],
["короткий","short"],["быстрый","fast / quick"],["медленный","slow"],
["тяжёлый","heavy / difficult"],["лёгкий","light / easy"],
["сильный","strong"],["слабый","weak"],["красивый","beautiful"],
["умный","smart / clever"],["глупый","stupid / foolish"],
["добрый","kind / good"],["злой","angry / evil / mean"],
["важный","important"],["нужный","necessary / needed"],
["странный","strange / odd"],["простой","simple / plain"],
["сложный","complex / difficult"],["правый","right / correct"],
["левый","left"],["открытый","open"],["закрытый","closed"],
["свободный","free / available"],["занятый","busy / occupied"],
["богатый","rich"],["бедный","poor"],["живой","alive / lively"],
["мёртвый","dead"],["настоящий","real / genuine / present"],
["целый","whole / entire"],["пустой","empty"],["полный","full / complete"],
["тихий","quiet / calm"],["громкий","loud"],["чистый","clean / pure"],
["грязный","dirty"],["светлый","bright / light"],["тёмный","dark"],
["горячий","hot"],["холодный","cold"],["тёплый","warm"],
["прохладный","cool"],["сухой","dry"],["мокрый","wet"],
["похожий","similar / resembling"],["разный","different / various"],
["общий","common / general / shared"],["главный","main / chief"],
["особый","special / particular"],["такой","such / so"],
["другой","other / another / different"],["каждый","each / every"],
["любой","any / every"],["весь","all / whole / entire"],
["многие","many (people/things)"],["несколько","several / a few"],
["один","one / alone / single"],["единственный","the only / sole"],
["следующий","next / following"],["прошлый","past / last"],
["будущий","future / upcoming"],["современный","modern / contemporary"],
["известный","famous / known"],["возможный","possible"],
["необходимый","necessary / essential"],["интересный","interesting"],
["красный","red"],["синий","dark blue"],["голубой","light blue"],
["зелёный","green"],["жёлтый","yellow"],["белый","white"],
["чёрный","black"],["серый","grey"],["коричневый","brown"],
["оранжевый","orange"],["розовый","pink"],["фиолетовый","purple"],
// ── People & family ──────────────────────────────────────────────────────────
["человек","person / man"],["люди","people"],["мужчина","man / male"],
["женщина","woman / female"],["ребёнок","child"],["дети","children"],
["мальчик","boy"],["девочка","girl"],["подросток","teenager"],
["взрослый","adult / grown-up"],["старик","old man"],["старушка","old woman"],
["друг","friend (m)"],["подруга","friend (f)"],["враг","enemy"],
["сосед","neighbour"],["гость","guest"],["незнакомец","stranger"],
["начальник","boss / chief"],["учитель","teacher"],["ученик","pupil / student"],
["студент","student (university)"],["врач","doctor"],["медсестра","nurse"],
["солдат","soldier"],["полицейский","police officer"],["президент","president"],
["король","king"],["семья","family"],["мать","mother"],["отец","father"],
["сын","son"],["дочь","daughter"],["брат","brother"],["сестра","sister"],
["муж","husband"],["жена","wife"],["бабушка","grandmother"],
["дедушка","grandfather"],["внук","grandson"],["внучка","granddaughter"],
["дядя","uncle"],["тётя","aunt"],["племянник","nephew"],
["племянница","niece"],["родители","parents"],["ребята","guys / kids"],
// ── Time ────────────────────────────────────────────────────────────────────
["год","year"],["время","time"],["день","day"],["ночь","night"],
["утро","morning"],["вечер","evening"],["час","hour"],["минута","minute"],
["секунда","second"],["неделя","week"],["месяц","month"],["сезон","season"],
["весна","spring"],["лето","summer"],["осень","autumn / fall"],["зима","winter"],
["понедельник","Monday"],["вторник","Tuesday"],["среда","Wednesday"],
["четверг","Thursday"],["пятница","Friday"],["суббота","Saturday"],
["воскресенье","Sunday"],["январь","January"],["февраль","February"],
["март","March"],["апрель","April"],["май","May"],["июнь","June"],
["июль","July"],["август","August"],["сентябрь","September"],
["октябрь","October"],["ноябрь","November"],["декабрь","December"],
["сегодня","today"],["вчера","yesterday"],["завтра","tomorrow"],
["позавчера","the day before yesterday"],["послезавтра","the day after tomorrow"],
["скоро","soon"],["давно","long ago"],["недавно","recently"],["сейчас","now"],
["прошлое","the past"],["будущее","the future"],["настоящее","the present"],
["начало","beginning / start"],["конец","end / finish"],["середина","middle"],
["период","period"],["момент","moment"],["эпоха","era / epoch"],
// ── Place & space ────────────────────────────────────────────────────────────
["место","place / spot / seat"],["дом","house / home"],["страна","country"],
["город","city / town"],["деревня","village / countryside"],
["улица","street"],["дорога","road / way / journey"],["путь","path / way"],
["мир","world / peace"],["земля","earth / land / ground"],
["небо","sky / heaven"],["море","sea"],["океан","ocean"],["река","river"],
["озеро","lake"],["лес","forest"],["гора","mountain"],["поле","field"],
["остров","island"],["берег","shore / bank / coast"],["центр","centre"],
["север","north"],["юг","south"],["восток","east"],["запад","west"],
["угол","corner / angle"],["граница","border / boundary / limit"],
["площадь","square / area / space"],["здание","building"],["комната","room"],
["кухня","kitchen"],["ванная","bathroom"],["спальня","bedroom"],
["окно","window"],["дверь","door"],["стена","wall"],["пол","floor"],
["потолок","ceiling"],["стол","table"],["стул","chair"],["кровать","bed"],
["шкаф","wardrobe / cabinet"],["диван","sofa / couch"],["лестница","stairs"],
["крыша","roof"],["двор","yard / courtyard"],["сад","garden"],
["парк","park"],["мост","bridge"],["вокзал","railway station"],
["аэропорт","airport"],["больница","hospital"],["школа","school"],
["магазин","shop / store"],["ресторан","restaurant"],["музей","museum"],
["театр","theatre"],["офис","office"],["церковь","church"],
// ── Body ────────────────────────────────────────────────────────────────────
["рука","hand / arm"],["нога","leg / foot"],["голова","head"],
["лицо","face"],["глаз","eye"],["ухо","ear"],["нос","nose"],
["рот","mouth"],["зуб","tooth"],["язык","tongue / language"],
["шея","neck"],["плечо","shoulder"],["спина","back"],
["грудь","chest / breast"],["живот","stomach / belly"],["сердце","heart"],
["кровь","blood"],["кожа","skin"],["волосы","hair"],["палец","finger / toe"],
["колено","knee"],["локоть","elbow"],["горло","throat"],["мозг","brain"],
// ── Common nouns – abstract ───────────────────────────────────────────────────
["жизнь","life"],["смерть","death"],["любовь","love"],["дело","matter / business / case"],
["слово","word"],["вопрос","question"],["ответ","answer"],
["проблема","problem"],["случай","case / occasion / event"],
["часть","part / section"],["вещь","thing"],["работа","work / job"],
["сила","strength / force / power"],["власть","power / authority"],
["право","right / law"],["закон","law"],["порядок","order"],
["система","system"],["история","history / story"],["наука","science"],
["искусство","art"],["музыка","music"],["книга","book"],["письмо","letter"],
["мысль","thought"],["идея","idea"],["план","plan"],["цель","goal / aim"],
["результат","result"],["причина","reason / cause"],["пример","example"],
["условие","condition"],["возможность","possibility / opportunity"],
["способ","way / method"],["процесс","process"],["движение","movement"],
["изменение","change"],["раз","time / once"],["вид","type / view / appearance"],
["смысл","meaning / sense / point"],["роль","role"],["место","place / role"],
["уровень","level"],["ошибка","mistake / error"],["успех","success"],
["неудача","failure"],["удача","luck"],["судьба","fate / destiny"],
["счастье","happiness"],["радость","joy"],["горе","grief / sorrow"],
["страх","fear"],["опасность","danger"],["надежда","hope"],["мечта","dream"],
["вера","faith / belief"],["свобода","freedom"],["война","war"],
["победа","victory"],["поражение","defeat"],["мир","peace / world"],
["общество","society"],["культура","culture"],["характер","character / personality"],
["отношение","attitude / relationship"],["связь","connection / communication"],
["разница","difference"],["похожесть","similarity"],["рост","growth / height"],
["развитие","development"],["решение","decision / solution"],
["знание","knowledge"],["опыт","experience"],["память","memory"],
["внимание","attention"],["интерес","interest"],["важность","importance"],
// ── Common nouns – objects & things ──────────────────────────────────────────
["машина","car / machine"],["телефон","phone"],["компьютер","computer"],
["деньги","money"],["цена","price / cost"],["ключ","key"],
["бумага","paper"],["ручка","pen / handle"],["стекло","glass (material)"],
["огонь","fire"],["свет","light"],["тень","shadow / shade"],
["звук","sound"],["запах","smell / scent"],["вкус","taste"],
["цвет","colour"],["форма","form / shape"],["размер","size"],
["одежда","clothes"],["платье","dress"],["рубашка","shirt"],
["брюки","trousers / pants"],["обувь","footwear / shoes"],["шапка","hat / cap"],
["пальто","coat"],["куртка","jacket"],["сумка","bag"],["кошелёк","wallet"],
["часы","watch / clock"],["кольцо","ring"],["очки","glasses / spectacles"],
// ── Food & drink ─────────────────────────────────────────────────────────────
["еда","food"],["суп","soup"],["хлеб","bread"],["молоко","milk"],
["мясо","meat"],["рыба","fish"],["яйцо","egg"],["овощ","vegetable"],
["фрукт","fruit"],["яблоко","apple"],["картофель","potato"],
["лук","onion"],["чеснок","garlic"],["морковь","carrot"],["рис","rice"],
["сыр","cheese"],["масло","butter / oil"],["сахар","sugar"],["соль","salt"],
["чай","tea"],["кофе","coffee"],["вода","water"],["сок","juice"],
["пиво","beer"],["вино","wine"],["завтрак","breakfast"],
["обед","lunch / dinner"],["ужин","supper / dinner"],["торт","cake"],
["конфета","candy / sweet"],["шоколад","chocolate"],
// ── Nature & animals ─────────────────────────────────────────────────────────
["солнце","sun"],["луна","moon"],["звезда","star"],["облако","cloud"],
["дождь","rain"],["снег","snow"],["ветер","wind"],["погода","weather"],
["природа","nature"],["животное","animal"],["собака","dog"],["кошка","cat"],
["птица","bird"],["лошадь","horse"],["корова","cow"],["свинья","pig"],
["медведь","bear"],["волк","wolf"],["лиса","fox"],["заяц","hare / rabbit"],
["орёл","eagle"],["дерево","tree"],["цветок","flower"],["трава","grass"],
["лист","leaf"],["камень","stone / rock"],["земля","earth / soil / ground"],
// ── Health ───────────────────────────────────────────────────────────────────
["здоровье","health"],["болезнь","illness / disease"],
["лекарство","medicine / medication"],["боль","pain"],
["усталость","fatigue / tiredness"],["сон","sleep / dream"],["аппетит","appetite"],
// ── Education & work ─────────────────────────────────────────────────────────
["урок","lesson"],["задание","task / assignment"],["экзамен","exam"],
["оценка","grade / evaluation"],["задача","task / problem"],
["встреча","meeting / encounter"],["проект","project"],
["профессия","profession / occupation"],["университет","university"],
// ── Common phrases ───────────────────────────────────────────────────────────
["спасибо","thank you"],["пожалуйста","please / you're welcome"],
["извини","sorry / excuse me (inf)"],["извините","sorry / excuse me (formal)"],
["здравствуйте","hello (formal)"],["привет","hi / hello (informal)"],
["пока","bye / so long"],["до свидания","goodbye"],["да","yes"],
["ладно","okay / alright"],["хватит","enough / stop it"],
["понятно","I see / understood"],["правда","truth / really?"],
["точно","exactly / definitely"],["не знаю","I don't know"],
];
