// [russian, english, grammar_tag, example_ru, example_en]
// tags: м/ж/с/мн = noun gender | несов/сов = verb aspect | "" = other
const RUSSIAN_WORDS = [
["и","and","","Маша и Ваня друзья.","Masha and Vanya are friends."],
["в","in / at","","Она живёт в Москве.","She lives in Moscow."],
["не","not","","Я не понимаю.","I don't understand."],
["на","on / at","","Книга на столе.","The book is on the table."],
["я","I","","Я учу русский язык.","I am learning Russian."],
["что","what / that","","Что ты делаешь?","What are you doing?"],
["с","with / from","","Я иду с другом.","I am going with a friend."],
["он","he","","Он живёт здесь.","He lives here."],
["как","how / as / like","","Как тебя зовут?","What is your name?"],
["но","but","","Я хочу, но не могу.","I want to, but I can't."],
["это","this / it","","Это мой дом.","This is my house."],
["она","she","","Она говорит по-русски.","She speaks Russian."],
["всё","everything / all","","Всё в порядке.","Everything is fine."],
["по","along / by","","Иди прямо по улице.","Walk straight along the street."],
["его","his / him","","Это его книга.","This is his book."],
["за","for / behind","","Спасибо за помощь.","Thank you for the help."],
["мы","we","","Мы идём в кино.","We are going to the cinema."],
["из","from / out of","","Я из России.","I am from Russia."],
["а","and / but","","Я остаюсь, а ты идёшь.","I'm staying, but you're going."],
["они","they","","Они живут рядом.","They live nearby."],
["то","that / then","","Если хочешь, то иди.","If you want, then go."],
["от","from / away from","","Далеко от дома.","Far from home."],
["так","so / thus","","Так нельзя делать.","You can't do it like that."],
["же","(emphatic particle)","","Иди же сюда!","Come here already!"],
["тот","that one","","Тот человек ушёл.","That person left."],
["бы","would (conditional)","","Я бы хотел чаю.","I would like some tea."],
["к","to / towards","","Подойди к окну.","Come up to the window."],
["ещё","still / yet / more","","Я ещё здесь.","I'm still here."],
["уже","already","","Он уже пришёл.","He has already arrived."],
["до","until / before","","До свидания!","Goodbye!"],
["вы","you (plural / formal)","","Вы говорите по-английски?","Do you speak English?"],
["или","or","","Чай или кофе?","Tea or coffee?"],
["который","which / who","","Дом, который стоит там.","The house that stands there."],
["если","if","","Если хочешь, скажи мне.","If you want, tell me."],
["при","at / by / under","","При входе стоит охранник.","There is a guard at the entrance."],
["наш","our","","Наш дом большой.","Our house is big."],
["без","without","","Кофе без сахара.","Coffee without sugar."],
["когда","when","","Когда ты придёшь?","When will you come?"],
["даже","even","","Он даже не позвонил.","He didn't even call."],
["вот","here is","","Вот мой паспорт.","Here is my passport."],
["ли","whether (particle)","","Не знаю, придёт ли он.","I don't know whether he'll come."],
["там","there","","Он живёт там.","He lives there."],
["нет","no / there is no","","Нет, я не хочу.","No, I don't want to."],
["её","her / hers","","Это её книга.","This is her book."],
["их","their / them","","Это их дом.","This is their house."],
["об","about","","Расскажи об этом.","Tell me about this."],
["тоже","also / too","","Я тоже хочу.","I want to as well."],
["только","only / just","","Только не это!","Anything but that!"],
["себя","oneself","","Он думает только о себе.","He only thinks about himself."],
["свой","one's own","","У каждого есть своё мнение.","Everyone has their own opinion."],
["сам","oneself / self","","Я сам это сделал.","I did it myself."],
["тогда","then / at that time","","Тогда я был молодым.","Back then I was young."],
["здесь","here","","Подожди здесь.","Wait here."],
["потом","then / afterwards","","Сначала поешь, потом иди.","Eat first, then go."],
["всегда","always","","Она всегда улыбается.","She always smiles."],
["очень","very","","Это очень интересно.","This is very interesting."],
["теперь","now / from now on","","Теперь я понимаю.","Now I understand."],
["где","where","","Где ты живёшь?","Where do you live?"],
["куда","where to","","Куда ты идёшь?","Where are you going?"],
["откуда","where from","","Откуда ты?","Where are you from?"],
["почему","why","","Почему ты плачешь?","Why are you crying?"],
["зачем","what for","","Зачем ты это сказал?","Why did you say that?"],
["сколько","how much / how many","","Сколько это стоит?","How much does this cost?"],
["много","a lot / many","","У неё много друзей.","She has a lot of friends."],
["мало","little / few","","У меня мало времени.","I have little time."],
["больше","more / no longer","","Дай мне больше времени.","Give me more time."],
["меньше","less / fewer","","Ешь меньше сахара.","Eat less sugar."],
["лучше","better","","Сегодня лучше, чем вчера.","Today is better than yesterday."],
["хуже","worse","","Стало хуже.","It got worse."],
["вместе","together","","Мы вместе учимся.","We study together."],
["снова","again","","Попробуй снова.","Try again."],
["опять","again","","Он опять опоздал.","He was late again."],
["вдруг","suddenly","","Вдруг пошёл дождь.","Suddenly it started raining."],
["сразу","at once / immediately","","Позвони мне сразу.","Call me immediately."],
["наконец","finally","","Наконец ты пришёл!","You finally came!"],
["совсем","completely / at all","","Я совсем не устал.","I'm not tired at all."],
["почти","almost","","Я почти готов.","I'm almost ready."],
["просто","simply / just","","Просто скажи правду.","Just tell the truth."],
["именно","exactly / precisely","","Именно это я имел в виду.","That's exactly what I meant."],
["конечно","of course","","Конечно, я помогу.","Of course I'll help."],
["может быть","maybe / perhaps","","Может быть, завтра.","Maybe tomorrow."],
["действительно","really / indeed","","Он действительно умный.","He really is smart."],
["вообще","in general / at all","","Вообще-то это неправда.","Actually, that's not true."],
["например","for example","","Например, возьми яблоко.","For example, take an apple."],
["поэтому","therefore","","Я устал, поэтому лягу спать.","I'm tired, so I'll go to sleep."],
["однако","however","","Однако это неправда.","However, that's not true."],
["также","also / as well","","Он также говорит по-французски.","He also speaks French."],
["хотя","although","","Хотя холодно, он без пальто.","Although it's cold, he has no coat."],
["чтобы","in order to","","Учусь, чтобы говорить по-русски.","I study in order to speak Russian."],
["потому что","because","","Я остался, потому что хотел.","I stayed because I wanted to."],
["никогда","never","","Я никогда не был в России.","I have never been to Russia."],
["иногда","sometimes","","Иногда я читаю вечером.","Sometimes I read in the evening."],
["обычно","usually","","Обычно я встаю в семь.","I usually get up at seven."],
["часто","often","","Она часто звонит маме.","She often calls her mum."],
["редко","rarely","","Он редко ест мясо.","He rarely eats meat."],
["везде","everywhere","","Везде слышна музыка.","Music can be heard everywhere."],
["нигде","nowhere","","Нигде не могу найти ключи.","I can't find the keys anywhere."],
["далеко","far","","Школа далеко от дома.","The school is far from home."],
["близко","near / close","","Магазин здесь близко.","The shop is close by."],
["рядом","next to / nearby","","Он сидит рядом со мной.","He is sitting next to me."],
["вперёд","forward","","Иди вперёд.","Go forward."],
["назад","back / backwards","","Шаг назад.","A step back."],
["вверх","upward","","Подними руку вверх.","Raise your hand up."],
["вниз","downward","","Иди вниз по лестнице.","Go down the stairs."],
["прямо","straight / directly","","Иди прямо.","Go straight ahead."],
["налево","to the left","","Поверни налево.","Turn left."],
["направо","to the right","","Поверни направо.","Turn right."],
["сюда","here (to here)","","Иди сюда.","Come here."],
["туда","there (to there)","","Я иду туда.","I'm going there."],
// ── Numbers ──────────────────────────────────────────────────────────────────
["один","one","","У меня один брат.","I have one brother."],
["два","two","","Два кофе, пожалуйста.","Two coffees, please."],
["три","three","","Три кошки спят.","Three cats are sleeping."],
["четыре","four","","В семье четыре человека.","There are four people in the family."],
["пять","five","","У меня пять уроков.","I have five lessons."],
["шесть","six","","В неделе шесть рабочих дней.","There are six working days in the week."],
["семь","seven","","Семь часов утра.","Seven o'clock in the morning."],
["восемь","eight","","Восемь минут пешком.","Eight minutes on foot."],
["девять","nine","","Девять месяцев.","Nine months."],
["десять","ten","","У меня десять пальцев.","I have ten fingers."],
["одиннадцать","eleven","","Ему одиннадцать лет.","He is eleven years old."],
["двенадцать","twelve","","Двенадцать месяцев в году.","There are twelve months in a year."],
["тринадцать","thirteen","","Ей тринадцать лет.","She is thirteen years old."],
["четырнадцать","fourteen","","Четырнадцать дней — две недели.","Fourteen days is two weeks."],
["пятнадцать","fifteen","","Пятнадцать минут.","Fifteen minutes."],
["двадцать","twenty","","Мне двадцать лет.","I am twenty years old."],
["тридцать","thirty","","Тридцать дней в апреле.","There are thirty days in April."],
["сорок","forty","","Ему сорок лет.","He is forty years old."],
["пятьдесят","fifty","","Пятьдесят рублей.","Fifty roubles."],
["шестьдесят","sixty","","Шестьдесят минут в часе.","There are sixty minutes in an hour."],
["семьдесят","seventy","","Ей семьдесят лет.","She is seventy years old."],
["восемьдесят","eighty","","Восемьдесят процентов.","Eighty percent."],
["девяносто","ninety","","Девяносто секунд.","Ninety seconds."],
["сто","hundred","","Сто рублей.","One hundred roubles."],
["тысяча","thousand","ж","Тысяча человек.","A thousand people."],
["миллион","million","м","Миллион звёзд на небе.","A million stars in the sky."],
["первый","first","","Первый день весны.","The first day of spring."],
["второй","second","","Второй этаж.","The second floor."],
["третий","third","","Третий раз.","The third time."],
["последний","last","","Последний автобус ушёл.","The last bus has left."],
["следующий","next / following","","Следующая остановка — центр.","Next stop — the centre."],
// ── Core verbs ───────────────────────────────────────────────────────────────
["быть","to be","несов","Он хочет быть врачом.","He wants to be a doctor."],
["стать","to become","сов","Она стала учителем.","She became a teacher."],
["есть","to eat","несов","Дети едят суп.","The children are eating soup."],
["иметь","to have","несов","Ты имеешь право знать.","You have the right to know."],
["мочь","to be able to / can","несов","Я не могу прийти сегодня.","I can't come today."],
["хотеть","to want","несов","Я хочу спать.","I want to sleep."],
["знать","to know","несов","Ты знаешь его имя?","Do you know his name?"],
["думать","to think","несов","Я думаю о тебе.","I am thinking about you."],
["говорить","to speak / say","несов","Он говорит по-русски.","He speaks Russian."],
["сказать","to say / tell","сов","Она сказала правду.","She told the truth."],
["делать","to do / make","несов","Что ты делаешь?","What are you doing?"],
["сделать","to do / make","сов","Я сделал всё задание.","I finished all the homework."],
["идти","to go (on foot)","несов","Он идёт в школу.","He is going to school."],
["ходить","to go / walk","несов","Она ходит в спортзал каждый день.","She goes to the gym every day."],
["ехать","to go (by transport)","несов","Мы едем в Москву.","We are going to Moscow."],
["ездить","to travel","несов","Он часто ездит в командировки.","He often travels on business."],
["бежать","to run","несов","Мальчик бежит домой.","The boy is running home."],
["бегать","to run (repeated)","несов","Она бегает каждое утро.","She runs every morning."],
["давать","to give","несов","Мама даёт ребёнку яблоко.","Mum gives the child an apple."],
["дать","to give","сов","Дай мне ручку.","Give me a pen."],
["брать","to take","несов","Он берёт зонт — идёт дождь.","He takes an umbrella — it's raining."],
["взять","to take","сов","Она взяла мою книгу.","She took my book."],
["видеть","to see","несов","Я вижу гору вдали.","I can see a mountain in the distance."],
["смотреть","to look / watch","несов","Они смотрят фильм.","They are watching a film."],
["слышать","to hear","несов","Ты слышишь музыку?","Can you hear the music?"],
["слушать","to listen","несов","Я слушаю подкаст.","I am listening to a podcast."],
["читать","to read","несов","Она читает книгу.","She is reading a book."],
["писать","to write","несов","Он пишет письмо.","He is writing a letter."],
["понимать","to understand","несов","Я понимаю тебя.","I understand you."],
["понять","to understand","сов","Ты понял задание?","Did you understand the task?"],
["помнить","to remember","несов","Ты помнишь её имя?","Do you remember her name?"],
["забыть","to forget","сов","Я забыл зонт дома.","I forgot my umbrella at home."],
["забывать","to forget","несов","Он всегда забывает ключи.","He always forgets his keys."],
["верить","to believe","несов","Я верю тебе.","I believe you."],
["любить","to love / like","несов","Она любит читать.","She loves to read."],
["жить","to live","несов","Они живут в деревне.","They live in a village."],
["умереть","to die","сов","Старый пёс умер.","The old dog died."],
["родиться","to be born","сов","Он родился в мае.","He was born in May."],
["работать","to work","несов","Она работает врачом.","She works as a doctor."],
["учиться","to study / learn","несов","Он учится в университете.","He studies at university."],
["играть","to play","несов","Дети играют во дворе.","The children are playing in the yard."],
["помочь","to help","сов","Ты можешь мне помочь?","Can you help me?"],
["помогать","to help","несов","Она помогает маме.","She helps her mum."],
["найти","to find","сов","Я наконец нашёл ключи.","I finally found my keys."],
["искать","to search / look for","несов","Они ищут работу.","They are looking for work."],
["открыть","to open","сов","Открой окно, пожалуйста.","Open the window, please."],
["закрыть","to close","сов","Закрой дверь.","Close the door."],
["начать","to begin","сов","Урок начался в девять.","The lesson began at nine."],
["начинать","to begin","несов","Он начинает работу в восемь.","He begins work at eight."],
["кончить","to finish","сов","Она кончила читать книгу.","She finished reading the book."],
["продолжать","to continue","несов","Продолжай, я слушаю.","Continue, I'm listening."],
["остановить","to stop","сов","Он остановил машину.","He stopped the car."],
["остаться","to stay / remain","сов","Она осталась дома.","She stayed at home."],
["оставаться","to stay / remain","несов","Он остаётся в Москве.","He is staying in Moscow."],
["вернуться","to return","сов","Папа вернулся домой.","Dad came back home."],
["возвращаться","to return","несов","Она возвращается поздно.","She returns late."],
["приходить","to come / arrive","несов","Он приходит каждый вечер.","He comes every evening."],
["прийти","to come / arrive","сов","Она пришла вовремя.","She arrived on time."],
["уходить","to leave","несов","Он уходит рано утром.","He leaves early in the morning."],
["уйти","to leave","сов","Она уже ушла.","She has already left."],
["входить","to enter","несов","Не входи без стука.","Don't enter without knocking."],
["выходить","to go out / exit","несов","Она выходит на следующей станции.","She gets off at the next station."],
["подходить","to approach","несов","Не подходи к огню.","Don't approach the fire."],
["встретить","to meet","сов","Я встретил старого друга.","I met an old friend."],
["встречать","to meet","несов","Он встречает гостей у входа.","He greets guests at the entrance."],
["ждать","to wait","несов","Подожди меня.","Wait for me."],
["спросить","to ask","сов","Она спросила дорогу.","She asked for directions."],
["спрашивать","to ask","несов","Он часто спрашивает совета.","He often asks for advice."],
["ответить","to answer","сов","Ответь на вопрос.","Answer the question."],
["отвечать","to answer","несов","Она отвечает на письма.","She answers letters."],
["рассказать","to tell / narrate","сов","Расскажи мне об этом.","Tell me about this."],
["объяснить","to explain","сов","Объясни мне это правило.","Explain this rule to me."],
["показать","to show","сов","Покажи мне карту.","Show me the map."],
["показывать","to show","несов","Она показывает фотографии.","She is showing photos."],
["позвонить","to call / phone","сов","Позвони мне вечером.","Call me in the evening."],
["купить","to buy","сов","Я купил хлеб.","I bought bread."],
["покупать","to buy","несов","Она покупает продукты раз в неделю.","She buys groceries once a week."],
["продать","to sell","сов","Он продал машину.","He sold his car."],
["получить","to receive / get","сов","Я получил письмо.","I received a letter."],
["получать","to receive","несов","Она получает зарплату раз в месяц.","She gets paid once a month."],
["использовать","to use","несов","Он использует словарь.","He uses a dictionary."],
["создать","to create","сов","Художник создал картину.","The artist created a painting."],
["строить","to build","несов","Они строят новый дом.","They are building a new house."],
["решить","to decide / solve","сов","Я решил задачу.","I solved the problem."],
["решать","to decide / solve","несов","Он решает задачи быстро.","He solves problems quickly."],
["считать","to count / consider","несов","Я считаю это правильным.","I consider this correct."],
["узнать","to find out / recognise","сов","Я узнал его сразу.","I recognised him immediately."],
["узнавать","to find out","несов","Она узнаёт новое каждый день.","She learns something new every day."],
["выбрать","to choose","сов","Выбери себе книгу.","Choose a book for yourself."],
["выбирать","to choose","несов","Ты долго выбираешь.","You take a long time to choose."],
["изменить","to change","сов","Он изменил своё мнение.","He changed his mind."],
["стоить","to cost / be worth","несов","Сколько стоит билет?","How much does the ticket cost?"],
["казаться","to seem","несов","Это кажется простым.","This seems simple."],
["называться","to be called","несов","Как называется этот город?","What is this city called?"],
["происходить","to happen","несов","Что здесь происходит?","What is happening here?"],
["появляться","to appear","несов","Солнце появилось из-за туч.","The sun appeared from behind the clouds."],
["исчезать","to disappear","несов","Туман исчезает утром.","The fog disappears in the morning."],
["расти","to grow","несов","Дерево растёт быстро.","The tree grows fast."],
["падать","to fall","несов","Снег падает тихо.","Snow falls quietly."],
["подниматься","to rise / go up","несов","Солнце поднимается на востоке.","The sun rises in the east."],
["двигаться","to move","несов","Поезд двигается медленно.","The train is moving slowly."],
["бояться","to be afraid","несов","Она боится темноты.","She is afraid of the dark."],
["радоваться","to rejoice / be glad","несов","Дети радуются снегу.","The children are happy about the snow."],
["смеяться","to laugh","несов","Они смеются над шуткой.","They are laughing at the joke."],
["плакать","to cry","несов","Ребёнок плачет.","The child is crying."],
["кричать","to shout","несов","Не кричи на меня!","Don't shout at me!"],
["петь","to sing","несов","Она красиво поёт.","She sings beautifully."],
["танцевать","to dance","несов","Они танцуют всю ночь.","They dance all night."],
["готовить","to cook / prepare","несов","Папа готовит ужин.","Dad is cooking dinner."],
["пить","to drink","несов","Она пьёт чай каждое утро.","She drinks tea every morning."],
["спать","to sleep","несов","Малыш спит.","The baby is sleeping."],
["отдыхать","to rest","несов","В воскресенье мы отдыхаем.","On Sunday we rest."],
["зависеть","to depend","несов","Это зависит от тебя.","It depends on you."],
["соглашаться","to agree","несов","Я соглашаюсь с тобой.","I agree with you."],
["отказываться","to refuse","несов","Она отказывается помочь.","She refuses to help."],
["предлагать","to suggest / offer","несов","Предлагаю пойти пешком.","I suggest going on foot."],
["требовать","to demand","несов","Он требует ответа.","He demands an answer."],
["разрешать","to allow / permit","несов","Здесь разрешают курить?","Is smoking allowed here?"],
["запрещать","to forbid","несов","Здесь запрещают фотографировать.","Photography is forbidden here."],
["защищать","to defend / protect","несов","Он защищает свою семью.","He protects his family."],
["бороться","to fight / struggle","несов","Она борется с болезнью.","She is fighting the illness."],
["нести","to carry","несов","Она несёт тяжёлую сумку.","She is carrying a heavy bag."],
["положить","to put / place","сов","Положи книгу на стол.","Put the book on the table."],
["класть","to put / place","несов","Она кладёт вещи в шкаф.","She puts things in the wardrobe."],
["прятаться","to hide","несов","Кот прячется под кроватью.","The cat is hiding under the bed."],
["повторять","to repeat","несов","Повторяй за мной.","Repeat after me."],
["развиваться","to develop","несов","Город развивается быстро.","The city is developing fast."],
// ── Adjectives ───────────────────────────────────────────────────────────────
["большой","big / large","","У них большой дом.","They have a big house."],
["маленький","small / little","","Маленький щенок.","A little puppy."],
["новый","new","","Купила новый телефон.","She bought a new phone."],
["старый","old","","Это старый город.","This is an old city."],
["хороший","good","","Это хороший фильм.","This is a good film."],
["плохой","bad","","Плохая погода сегодня.","The weather is bad today."],
["молодой","young","","Молодой специалист.","A young specialist."],
["высокий","tall / high","","Он очень высокий.","He is very tall."],
["низкий","low / short","","Низкий потолок.","A low ceiling."],
["длинный","long","","У неё длинные волосы.","She has long hair."],
["короткий","short","","Короткий ответ.","A short answer."],
["быстрый","fast / quick","","Быстрый интернет.","Fast internet."],
["медленный","slow","","Медленный поезд.","A slow train."],
["тяжёлый","heavy / difficult","","Тяжёлая сумка.","A heavy bag."],
["лёгкий","light / easy","","Лёгкое задание.","An easy task."],
["сильный","strong","","Сильный ветер.","A strong wind."],
["слабый","weak","","Слабый чай.","Weak tea."],
["красивый","beautiful","","Красивый вид.","A beautiful view."],
["умный","smart / clever","","Умный ребёнок.","A smart child."],
["глупый","stupid / foolish","","Глупый вопрос.","A stupid question."],
["добрый","kind / good","","Добрый человек.","A kind person."],
["злой","angry / evil","","Злая собака.","An aggressive dog."],
["важный","important","","Важное решение.","An important decision."],
["нужный","necessary / needed","","Нужные документы.","The necessary documents."],
["странный","strange / odd","","Странный звук.","A strange sound."],
["простой","simple / plain","","Простой вопрос.","A simple question."],
["сложный","complex / difficult","","Сложная задача.","A complex task."],
["правый","right (direction)","","Правая рука.","The right hand."],
["левый","left","","Левая сторона.","The left side."],
["открытый","open","","Открытое окно.","An open window."],
["закрытый","closed","","Закрытая дверь.","A closed door."],
["свободный","free / available","","Свободное место.","A free seat."],
["занятый","busy / occupied","","Он очень занят.","He is very busy."],
["богатый","rich","","Богатый человек.","A rich person."],
["бедный","poor","","Бедная семья.","A poor family."],
["живой","alive / lively","","Кот живой.","The cat is alive."],
["мёртвый","dead","","Мёртвая тишина.","Dead silence."],
["настоящий","real / genuine","","Настоящий друг.","A true friend."],
["целый","whole / entire","","Целый день.","The whole day."],
["пустой","empty","","Пустой стакан.","An empty glass."],
["полный","full / complete","","Полный стакан воды.","A full glass of water."],
["тихий","quiet / calm","","Тихая ночь.","A quiet night."],
["громкий","loud","","Громкая музыка.","Loud music."],
["чистый","clean / pure","","Чистая вода.","Clean water."],
["грязный","dirty","","Грязные руки.","Dirty hands."],
["светлый","bright / light","","Светлая комната.","A bright room."],
["тёмный","dark","","Тёмное небо.","A dark sky."],
["горячий","hot","","Горячий кофе.","Hot coffee."],
["холодный","cold","","Холодная вода.","Cold water."],
["тёплый","warm","","Тёплый свитер.","A warm sweater."],
["прохладный","cool","","Прохладный вечер.","A cool evening."],
["сухой","dry","","Сухой климат.","A dry climate."],
["мокрый","wet","","Мокрые волосы.","Wet hair."],
["похожий","similar / resembling","","Они очень похожи.","They look very similar."],
["разный","different / various","","Разные мнения.","Different opinions."],
["общий","common / shared","","Общая комната.","A shared room."],
["главный","main / chief","","Главная улица.","The main street."],
["особый","special / particular","","Особый случай.","A special occasion."],
["такой","such / so","","Такой красивый день!","Such a beautiful day!"],
["другой","other / another","","Другой вариант.","Another option."],
["каждый","each / every","","Каждый день.","Every day."],
["любой","any / every","","В любое время.","At any time."],
["весь","all / whole","","Весь день шёл дождь.","It rained all day."],
["многие","many","","Многие люди согласны.","Many people agree."],
["несколько","several / a few","","Несколько минут.","A few minutes."],
["единственный","the only / sole","","Единственный выход.","The only way out."],
["современный","modern","","Современный город.","A modern city."],
["известный","famous / known","","Известный писатель.","A famous writer."],
["возможный","possible","","Возможный вариант.","A possible option."],
["необходимый","necessary / essential","","Необходимые условия.","Necessary conditions."],
["интересный","interesting","","Интересная книга.","An interesting book."],
["красный","red","","Красная роза.","A red rose."],
["синий","dark blue","","Синее море.","A dark blue sea."],
["голубой","light blue","","Голубые глаза.","Light blue eyes."],
["зелёный","green","","Зелёная трава.","Green grass."],
["жёлтый","yellow","","Жёлтые листья.","Yellow leaves."],
["белый","white","","Белый снег.","White snow."],
["чёрный","black","","Чёрный кот.","A black cat."],
["серый","grey","","Серое небо.","A grey sky."],
["коричневый","brown","","Коричневые глаза.","Brown eyes."],
["оранжевый","orange","","Оранжевый закат.","An orange sunset."],
["розовый","pink","","Розовые цветы.","Pink flowers."],
["фиолетовый","purple","","Фиолетовое платье.","A purple dress."],
// ── People & family ──────────────────────────────────────────────────────────
["человек","person / man","м","Добрый человек помог мне.","A kind person helped me."],
["люди","people","мн","Много людей на площади.","There are many people in the square."],
["мужчина","man / male","м","Высокий мужчина в пальто.","A tall man in a coat."],
["женщина","woman / female","ж","Красивая женщина улыбается.","A beautiful woman is smiling."],
["ребёнок","child","м","Маленький ребёнок плачет.","A small child is crying."],
["дети","children","мн","Дети играют в парке.","Children are playing in the park."],
["мальчик","boy","м","Мальчик читает книгу.","The boy is reading a book."],
["девочка","girl","ж","Девочка рисует.","The girl is drawing."],
["подросток","teenager","м","Подросток слушает музыку.","The teenager is listening to music."],
["взрослый","adult","м","Это для взрослых.","This is for adults."],
["старик","old man","м","Старик сидит на скамейке.","The old man sits on a bench."],
["старушка","old woman","ж","Старушка кормит голубей.","The old woman is feeding pigeons."],
["друг","friend (m)","м","Он мой лучший друг.","He is my best friend."],
["подруга","friend (f)","ж","Моя подруга живёт в Питере.","My friend lives in St. Petersburg."],
["враг","enemy","м","У него нет врагов.","He has no enemies."],
["сосед","neighbour","м","Мой сосед очень шумный.","My neighbour is very noisy."],
["гость","guest","м","У нас сегодня гости.","We have guests today."],
["начальник","boss / chief","м","Начальник на встрече.","The boss is at a meeting."],
["учитель","teacher","м","Учитель объясняет урок.","The teacher explains the lesson."],
["ученик","pupil / student","м","Ученик пишет на доске.","The pupil is writing on the board."],
["студент","student","м","Студент сдаёт экзамен.","The student is taking an exam."],
["врач","doctor","м","Врач осматривает пациента.","The doctor examines the patient."],
["медсестра","nurse","ж","Медсестра очень добрая.","The nurse is very kind."],
["солдат","soldier","м","Солдат стоит на посту.","The soldier stands guard."],
["полицейский","police officer","м","Полицейский помог нам.","The police officer helped us."],
["президент","president","м","Президент выступил по телевизору.","The president spoke on television."],
["король","king","м","Король живёт во дворце.","The king lives in the palace."],
["семья","family","ж","У меня большая семья.","I have a big family."],
["мать","mother","ж","Мать готовит обед.","The mother is cooking lunch."],
["отец","father","м","Отец читает газету.","The father is reading a newspaper."],
["сын","son","м","Мой сын учится в школе.","My son goes to school."],
["дочь","daughter","ж","Её дочь очень умная.","Her daughter is very smart."],
["брат","brother","м","Мой брат старше меня.","My brother is older than me."],
["сестра","sister","ж","Сестра живёт в другом городе.","My sister lives in another city."],
["муж","husband","м","Её муж — врач.","Her husband is a doctor."],
["жена","wife","ж","Его жена работает в школе.","His wife works at a school."],
["бабушка","grandmother","ж","Бабушка печёт пироги.","Grandma is baking pies."],
["дедушка","grandfather","м","Дедушка рассказывает истории.","Grandad tells stories."],
["внук","grandson","м","Внук навестил бабушку.","The grandson visited his grandmother."],
["внучка","granddaughter","ж","Внучка похожа на маму.","The granddaughter looks like her mum."],
["дядя","uncle","м","Дядя привёз подарки.","Uncle brought presents."],
["тётя","aunt","ж","Тётя живёт в Москве.","Aunt lives in Moscow."],
["родители","parents","мн","Мои родители в отпуске.","My parents are on holiday."],
// ── Time ─────────────────────────────────────────────────────────────────────
["год","year","м","В этом году лето жаркое.","This year summer is hot."],
["время","time","с","У меня нет времени.","I don't have time."],
["день","day","м","Хороший день.","A good day."],
["ночь","night","ж","Спокойной ночи!","Good night!"],
["утро","morning","с","Доброе утро!","Good morning!"],
["вечер","evening","м","Добрый вечер!","Good evening!"],
["час","hour","м","Жди меня один час.","Wait for me for one hour."],
["минута","minute","ж","Подожди одну минуту.","Wait one minute."],
["секунда","second","ж","Одну секунду!","One second!"],
["неделя","week","ж","На следующей неделе.","Next week."],
["месяц","month","м","Через месяц.","In a month."],
["весна","spring","ж","Весна пришла!","Spring has come!"],
["лето","summer","с","Летом мы едем на море.","In summer we go to the sea."],
["осень","autumn / fall","ж","Осенью листья желтеют.","In autumn the leaves turn yellow."],
["зима","winter","ж","Зимой холодно.","It's cold in winter."],
["понедельник","Monday","м","Встреча в понедельник.","The meeting is on Monday."],
["вторник","Tuesday","м","Во вторник занятия.","Classes are on Tuesday."],
["среда","Wednesday","ж","В среду я занят.","I'm busy on Wednesday."],
["четверг","Thursday","м","В четверг вечером.","On Thursday evening."],
["пятница","Friday","ж","Наконец-то пятница!","Finally Friday!"],
["суббота","Saturday","ж","В субботу отдыхаем.","We rest on Saturday."],
["воскресенье","Sunday","с","Воскресенье — выходной день.","Sunday is a day off."],
["январь","January","м","В январе холодно.","It's cold in January."],
["февраль","February","м","Февраль — короткий месяц.","February is a short month."],
["март","March","м","Март — первый месяц весны.","March is the first month of spring."],
["апрель","April","м","В апреле тает снег.","In April the snow melts."],
["май","May","м","Первого мая — праздник.","The first of May is a holiday."],
["июнь","June","м","В июне начинается лето.","Summer begins in June."],
["июль","July","м","Июль — самый жаркий месяц.","July is the hottest month."],
["август","August","м","В августе идут дожди.","It rains in August."],
["сентябрь","September","м","В сентябре начинается учёба.","School starts in September."],
["октябрь","October","м","В октябре листья падают.","Leaves fall in October."],
["ноябрь","November","м","В ноябре темно.","It's dark in November."],
["декабрь","December","м","Декабрь — последний месяц года.","December is the last month of the year."],
["сегодня","today","","Сегодня хорошая погода.","The weather is good today."],
["вчера","yesterday","","Вчера шёл дождь.","It rained yesterday."],
["завтра","tomorrow","","Завтра я буду дома.","Tomorrow I'll be at home."],
["скоро","soon","","Он скоро придёт.","He will come soon."],
["давно","long ago","","Это было давно.","That was a long time ago."],
["недавно","recently","","Она недавно переехала.","She moved recently."],
["сейчас","now","","Позвони мне сейчас.","Call me now."],
["начало","beginning / start","с","В начале было слово.","In the beginning was the word."],
["конец","end / finish","м","Конец фильма.","The end of the film."],
["середина","middle","ж","В середине ночи.","In the middle of the night."],
["момент","moment","м","В этот момент.","At this moment."],
// ── Place & space ─────────────────────────────────────────────────────────────
["место","place / spot / seat","с","Это моё место.","This is my seat."],
["дом","house / home","м","Идём домой.","Let's go home."],
["страна","country","ж","Я люблю свою страну.","I love my country."],
["город","city / town","м","Большой город.","A big city."],
["деревня","village / countryside","ж","Бабушка живёт в деревне.","Grandma lives in the village."],
["улица","street","ж","Шумная улица.","A noisy street."],
["дорога","road / way","ж","Дорога ведёт в город.","The road leads to the city."],
["путь","path / way","м","Долгий путь домой.","A long way home."],
["мир","world / peace","м","Во всём мире.","All over the world."],
["земля","earth / land","ж","Земля вращается вокруг Солнца.","The Earth revolves around the Sun."],
["небо","sky / heaven","с","Голубое небо.","A blue sky."],
["море","sea","с","Мы едем на море.","We're going to the sea."],
["океан","ocean","м","Тихий океан.","The Pacific Ocean."],
["река","river","ж","Волга — самая длинная река России.","The Volga is Russia's longest river."],
["озеро","lake","с","Байкал — самое глубокое озеро.","Baikal is the deepest lake."],
["лес","forest","м","В лесу тихо.","It's quiet in the forest."],
["гора","mountain","ж","Высокая гора.","A high mountain."],
["поле","field","с","Пшеничное поле.","A wheat field."],
["остров","island","м","Маленький остров.","A small island."],
["берег","shore / bank","м","Идём к берегу.","Let's go to the shore."],
["центр","centre","м","В центре города.","In the city centre."],
["север","north","м","На севере холодно.","It's cold in the north."],
["юг","south","м","Летом едем на юг.","In summer we go south."],
["восток","east","м","Солнце встаёт на востоке.","The sun rises in the east."],
["запад","west","м","Поезд едет на запад.","The train is going west."],
["угол","corner / angle","м","Стол стоит в углу.","The table is in the corner."],
["граница","border / boundary","ж","На границе проверяют паспорт.","They check passports at the border."],
["площадь","square / area","ж","Красная площадь в Москве.","Red Square in Moscow."],
["здание","building","с","Высокое здание.","A tall building."],
["комната","room","ж","Моя комната большая.","My room is big."],
["кухня","kitchen","ж","Мы едим на кухне.","We eat in the kitchen."],
["ванная","bathroom","ж","В ванной есть душ.","There is a shower in the bathroom."],
["спальня","bedroom","ж","Спальня на втором этаже.","The bedroom is on the second floor."],
["окно","window","с","Открой окно.","Open the window."],
["дверь","door","ж","Закрой дверь.","Close the door."],
["стена","wall","ж","Картина висит на стене.","The picture hangs on the wall."],
["пол","floor","м","Кот лежит на полу.","The cat is lying on the floor."],
["потолок","ceiling","м","Высокий потолок.","A high ceiling."],
["стол","table","м","Ужин на столе.","Dinner is on the table."],
["стул","chair","м","Сядь на стул.","Sit on the chair."],
["кровать","bed","ж","Иду спать в кровать.","I'm going to bed."],
["шкаф","wardrobe / cabinet","м","Одежда в шкафу.","The clothes are in the wardrobe."],
["диван","sofa / couch","м","Кот спит на диване.","The cat is sleeping on the sofa."],
["двор","yard / courtyard","м","Дети во дворе.","The children are in the yard."],
["сад","garden","м","Яблоня в саду.","The apple tree is in the garden."],
["парк","park","м","Гуляем в парке.","We're taking a walk in the park."],
["мост","bridge","м","Переходим мост.","We're crossing the bridge."],
["вокзал","railway station","м","Встретимся на вокзале.","We'll meet at the station."],
["аэропорт","airport","м","Такси до аэропорта.","A taxi to the airport."],
["больница","hospital","ж","Его везут в больницу.","He's being taken to hospital."],
["школа","school","ж","Дети идут в школу.","The children are going to school."],
["магазин","shop / store","м","Иду в магазин.","I'm going to the shop."],
["ресторан","restaurant","м","Ужин в ресторане.","Dinner at a restaurant."],
["музей","museum","м","Идём в музей.","Let's go to the museum."],
["театр","theatre","м","Спектакль в театре.","A show at the theatre."],
["офис","office","м","Он работает в офисе.","He works in an office."],
["церковь","church","ж","Красивая церковь.","A beautiful church."],
// ── Body ─────────────────────────────────────────────────────────────────────
["рука","hand / arm","ж","Дай мне руку.","Give me your hand."],
["нога","leg / foot","ж","У меня болит нога.","My leg hurts."],
["голова","head","ж","Болит голова.","I have a headache."],
["лицо","face","с","У неё красивое лицо.","She has a beautiful face."],
["глаз","eye","м","У него голубые глаза.","He has blue eyes."],
["ухо","ear","с","Говори тихо, у меня болит ухо.","Speak quietly, my ear hurts."],
["нос","nose","м","Нос у него красный.","His nose is red."],
["рот","mouth","м","Закрой рот.","Close your mouth."],
["зуб","tooth","м","Болит зуб.","I have a toothache."],
["язык","tongue / language","м","Высунь язык.","Stick out your tongue."],
["шея","neck","ж","Болит шея.","My neck hurts."],
["плечо","shoulder","с","Он положил руку мне на плечо.","He put his hand on my shoulder."],
["спина","back","ж","Болит спина.","My back hurts."],
["грудь","chest","ж","Боль в груди.","A pain in the chest."],
["живот","stomach / belly","м","Болит живот.","My stomach hurts."],
["сердце","heart","с","Моё сердце бьётся быстро.","My heart is beating fast."],
["кровь","blood","ж","Красная кровь.","Red blood."],
["кожа","skin","ж","Нежная кожа.","Soft skin."],
["волосы","hair","мн","У неё длинные волосы.","She has long hair."],
["палец","finger / toe","м","Порезал палец.","I cut my finger."],
["колено","knee","с","Болит колено.","My knee hurts."],
["горло","throat","с","Болит горло.","My throat hurts."],
["мозг","brain","м","Думай мозгом.","Use your brain."],
// ── Abstract nouns ───────────────────────────────────────────────────────────
["жизнь","life","ж","Жизнь прекрасна.","Life is beautiful."],
["смерть","death","ж","Смерть неизбежна.","Death is inevitable."],
["любовь","love","ж","Любовь побеждает всё.","Love conquers all."],
["дело","matter / business","с","Это не твоё дело.","This is none of your business."],
["слово","word","с","Одно слово.","One word."],
["вопрос","question","м","Хороший вопрос.","Good question."],
["ответ","answer","м","Нет ответа.","There is no answer."],
["проблема","problem","ж","Это большая проблема.","This is a big problem."],
["случай","case / occasion","м","В этом случае.","In this case."],
["часть","part / section","ж","Первая часть книги.","The first part of the book."],
["вещь","thing","ж","Это красивая вещь.","This is a beautiful thing."],
["работа","work / job","ж","Он ищет работу.","He is looking for work."],
["сила","strength / force","ж","У него много силы.","He has a lot of strength."],
["власть","power / authority","ж","Власть в руках народа.","Power is in the hands of the people."],
["право","right / law","с","Это твоё право.","This is your right."],
["закон","law","м","Уважай закон.","Respect the law."],
["порядок","order","м","Соблюдай порядок.","Keep order."],
["система","system","ж","Нужна новая система.","A new system is needed."],
["история","history / story","ж","Интересная история.","An interesting story."],
["наука","science","ж","Наука развивается.","Science is developing."],
["искусство","art","с","Он любит искусство.","He loves art."],
["музыка","music","ж","Я люблю музыку.","I love music."],
["книга","book","ж","Читай книги.","Read books."],
["письмо","letter","с","Получил письмо.","I received a letter."],
["мысль","thought","ж","Интересная мысль.","An interesting thought."],
["идея","idea","ж","Хорошая идея!","Good idea!"],
["план","plan","м","Какой у тебя план?","What is your plan?"],
["цель","goal / aim","ж","Поставь себе цель.","Set yourself a goal."],
["результат","result","м","Хороший результат.","A good result."],
["причина","reason / cause","ж","В чём причина?","What is the reason?"],
["пример","example","м","Хороший пример.","A good example."],
["возможность","possibility / opportunity","ж","Хорошая возможность.","A good opportunity."],
["способ","way / method","м","Есть другой способ.","There is another way."],
["процесс","process","м","Долгий процесс.","A long process."],
["движение","movement","с","Движение — жизнь.","Movement is life."],
["раз","time / once","м","Первый раз.","The first time."],
["вид","type / view","м","Красивый вид.","A beautiful view."],
["смысл","meaning / point","м","В чём смысл?","What is the point?"],
["роль","role","ж","Важная роль.","An important role."],
["уровень","level","м","Высокий уровень.","A high level."],
["ошибка","mistake / error","ж","Я сделал ошибку.","I made a mistake."],
["успех","success","м","Желаю успеха!","I wish you success!"],
["удача","luck","ж","Желаю удачи!","Good luck!"],
["судьба","fate / destiny","ж","Такова судьба.","Such is fate."],
["счастье","happiness","с","Желаю счастья.","I wish you happiness."],
["радость","joy","ж","Какая радость!","What joy!"],
["горе","grief / sorrow","с","Большое горе.","Great sorrow."],
["страх","fear","м","Без страха.","Without fear."],
["опасность","danger","ж","Это большая опасность.","This is a great danger."],
["надежда","hope","ж","Не теряй надежды.","Don't lose hope."],
["мечта","dream","ж","Моя мечта — путешествовать.","My dream is to travel."],
["вера","faith / belief","ж","Вера в лучшее.","Faith in something better."],
["свобода","freedom","ж","Свобода очень важна.","Freedom is very important."],
["война","war","ж","Война — это плохо.","War is bad."],
["победа","victory","ж","День победы.","Victory Day."],
["общество","society","с","Мы живём в обществе.","We live in society."],
["культура","culture","ж","Русская культура.","Russian culture."],
["характер","character / personality","м","Сильный характер.","A strong character."],
["отношение","attitude / relationship","с","Хорошее отношение.","A good attitude."],
["связь","connection / communication","ж","Нет связи.","There is no connection."],
["разница","difference","ж","В чём разница?","What is the difference?"],
["развитие","development","с","Быстрое развитие.","Rapid development."],
["решение","decision / solution","с","Приняли решение.","A decision was made."],
["знание","knowledge","с","Знание — сила.","Knowledge is power."],
["опыт","experience","м","Много опыта.","A lot of experience."],
["память","memory","ж","Хорошая память.","A good memory."],
["внимание","attention","с","Обрати внимание!","Pay attention!"],
["интерес","interest","м","Он проявил интерес.","He showed interest."],
// ── Objects & things ─────────────────────────────────────────────────────────
["машина","car / machine","ж","Он едет на машине.","He is going by car."],
["телефон","phone","м","Позвони на телефон.","Call on the phone."],
["компьютер","computer","м","Работаю на компьютере.","I work on a computer."],
["деньги","money","мн","У меня нет денег.","I have no money."],
["цена","price / cost","ж","Какая цена?","What is the price?"],
["ключ","key","м","Потерял ключ.","I lost the key."],
["бумага","paper","ж","Лист бумаги.","A sheet of paper."],
["ручка","pen / handle","ж","Дай мне ручку.","Give me a pen."],
["огонь","fire","м","Огонь горит.","The fire is burning."],
["свет","light","м","Включи свет.","Turn on the light."],
["звук","sound","м","Странный звук.","A strange sound."],
["запах","smell / scent","м","Приятный запах.","A pleasant smell."],
["вкус","taste","м","Хороший вкус.","A good taste."],
["цвет","colour","м","Любимый цвет.","Favourite colour."],
["размер","size","м","Какой размер?","What size?"],
["одежда","clothes","ж","Красивая одежда.","Beautiful clothes."],
["платье","dress","с","Она надела платье.","She put on a dress."],
["рубашка","shirt","ж","Белая рубашка.","A white shirt."],
["брюки","trousers / pants","мн","Чёрные брюки.","Black trousers."],
["обувь","footwear / shoes","ж","Сними обувь.","Take off your shoes."],
["шапка","hat / cap","ж","Надень шапку.","Put on your hat."],
["пальто","coat","с","Тёплое пальто.","A warm coat."],
["куртка","jacket","ж","Кожаная куртка.","A leather jacket."],
["сумка","bag","ж","Тяжёлая сумка.","A heavy bag."],
["кошелёк","wallet","м","Потерял кошелёк.","I lost my wallet."],
["часы","watch / clock","мн","Который час?","What time is it?"],
["очки","glasses","мн","Надень очки.","Put on your glasses."],
// ── Food & drink ─────────────────────────────────────────────────────────────
["еда","food","ж","Еда готова.","The food is ready."],
["суп","soup","м","Горячий суп.","Hot soup."],
["хлеб","bread","м","Свежий хлеб.","Fresh bread."],
["молоко","milk","с","Стакан молока.","A glass of milk."],
["мясо","meat","с","Жареное мясо.","Fried meat."],
["рыба","fish","ж","Жареная рыба.","Fried fish."],
["яйцо","egg","с","Варёное яйцо.","A boiled egg."],
["овощ","vegetable","м","Свежие овощи.","Fresh vegetables."],
["фрукт","fruit","м","Ешь фрукты.","Eat fruit."],
["яблоко","apple","с","Красное яблоко.","A red apple."],
["картофель","potato","м","Варёный картофель.","Boiled potato."],
["морковь","carrot","ж","Свежая морковь.","Fresh carrot."],
["рис","rice","м","Варёный рис.","Boiled rice."],
["сыр","cheese","м","Бутерброд с сыром.","A sandwich with cheese."],
["масло","butter / oil","с","Хлеб с маслом.","Bread with butter."],
["сахар","sugar","м","Кофе без сахара.","Coffee without sugar."],
["соль","salt","ж","Добавь соль.","Add salt."],
["чай","tea","м","Чашка чая.","A cup of tea."],
["кофе","coffee","м","Утренний кофе.","Morning coffee."],
["вода","water","ж","Стакан воды.","A glass of water."],
["сок","juice","м","Апельсиновый сок.","Orange juice."],
["пиво","beer","с","Холодное пиво.","Cold beer."],
["вино","wine","с","Красное вино.","Red wine."],
["завтрак","breakfast","м","Вкусный завтрак.","A delicious breakfast."],
["обед","lunch / dinner","м","Иди на обед.","Go to lunch."],
["ужин","supper / dinner","м","Ужин готов.","Dinner is ready."],
["торт","cake","м","Шоколадный торт.","A chocolate cake."],
["конфета","candy / sweet","ж","Вкусная конфета.","A delicious sweet."],
["шоколад","chocolate","м","Горький шоколад.","Dark chocolate."],
// ── Nature & animals ─────────────────────────────────────────────────────────
["солнце","sun","с","Яркое солнце.","A bright sun."],
["луна","moon","ж","Полная луна.","A full moon."],
["звезда","star","ж","Яркая звезда.","A bright star."],
["облако","cloud","с","Белое облако.","A white cloud."],
["дождь","rain","м","Идёт дождь.","It's raining."],
["снег","snow","м","Падает снег.","Snow is falling."],
["ветер","wind","м","Сильный ветер.","A strong wind."],
["погода","weather","ж","Хорошая погода.","Good weather."],
["природа","nature","ж","Красивая природа.","Beautiful nature."],
["животное","animal","с","Дикое животное.","A wild animal."],
["собака","dog","ж","Собака лает.","The dog is barking."],
["кошка","cat","ж","Кошка спит.","The cat is sleeping."],
["птица","bird","ж","Птица поёт.","The bird is singing."],
["лошадь","horse","ж","Быстрая лошадь.","A fast horse."],
["корова","cow","ж","Корова даёт молоко.","The cow gives milk."],
["медведь","bear","м","Большой медведь.","A big bear."],
["волк","wolf","м","Серый волк.","A grey wolf."],
["лиса","fox","ж","Хитрая лиса.","A cunning fox."],
["заяц","hare / rabbit","м","Белый заяц.","A white hare."],
["орёл","eagle","м","Орёл летит высоко.","The eagle flies high."],
["дерево","tree","с","Высокое дерево.","A tall tree."],
["цветок","flower","м","Красивый цветок.","A beautiful flower."],
["трава","grass","ж","Зелёная трава.","Green grass."],
["лист","leaf","м","Жёлтый лист.","A yellow leaf."],
["камень","stone / rock","м","Тяжёлый камень.","A heavy stone."],
// ── Health ───────────────────────────────────────────────────────────────────
["здоровье","health","с","Береги здоровье.","Take care of your health."],
["болезнь","illness / disease","ж","Серьёзная болезнь.","A serious illness."],
["лекарство","medicine","с","Принять лекарство.","To take medicine."],
["боль","pain","ж","Сильная боль.","A strong pain."],
["усталость","fatigue / tiredness","ж","Чувствую усталость.","I feel tired."],
["сон","sleep / dream","м","Крепкий сон.","A deep sleep."],
// ── Education & work ─────────────────────────────────────────────────────────
["урок","lesson","м","Интересный урок.","An interesting lesson."],
["задание","task / assignment","с","Сложное задание.","A difficult assignment."],
["экзамен","exam","м","Сдать экзамен.","To pass an exam."],
["оценка","grade / evaluation","ж","Хорошая оценка.","A good grade."],
["задача","task / problem","ж","Решить задачу.","To solve a problem."],
["встреча","meeting / encounter","ж","Деловая встреча.","A business meeting."],
["проект","project","м","Большой проект.","A big project."],
["профессия","profession","ж","Какая профессия?","What profession?"],
["университет","university","м","Учится в университете.","He studies at university."],
// ── Common phrases ────────────────────────────────────────────────────────────
["спасибо","thank you","","Большое спасибо!","Thank you very much!"],
["пожалуйста","please / you're welcome","","Подожди, пожалуйста.","Wait, please."],
["извини","sorry / excuse me (inf)","","Извини, я опоздал.","Sorry, I was late."],
["извините","sorry / excuse me (formal)","","Извините, как пройти на вокзал?","Excuse me, how do I get to the station?"],
["здравствуйте","hello (formal)","","Здравствуйте, я ищу врача.","Hello, I'm looking for a doctor."],
["привет","hi / hello","","Привет, как дела?","Hi, how are you?"],
["пока","bye / so long","","Пока, увидимся!","Bye, see you!"],
["до свидания","goodbye","","До свидания, спасибо за всё.","Goodbye, thank you for everything."],
["да","yes","","Да, конечно.","Yes, of course."],
["ладно","okay / alright","","Ладно, я согласен.","Alright, I agree."],
["хватит","enough / stop it","","Хватит шуметь!","Stop making noise!"],
["понятно","I see / understood","","Понятно, спасибо.","I see, thank you."],
["правда","truth / really","ж","Скажи правду.","Tell the truth."],
["точно","exactly / definitely","","Точно, ты прав.","Exactly, you're right."],
["не знаю","I don't know","","Не знаю, спроси его.","I don't know, ask him."],
];
